### ISSUE TITLE
PC Not Resetting Between Passes

### ISSUE THREAD

**Issue by SamBaker101** [SYSPROG-JLS/6502Asm#1]
I've been using this assembler for a project and finding it very helpful, thank you!

I have run into an issue using labels with branch commands though. My program is as follows: 

;   Sam Baker
;   10/2023
;   Tests stack operations
;   Written for use with asm6502 assembler
;
;
; Test:       BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS
;
;   Program: 

begin   SEC
        BCC LABEL
        LDA #$00
        STA $00
        CLC
        BCC LABEL
        LDA #$01
        STA $01
LABEL   LDA #$02
        STA $02
        CLC

When the program is assembled the pcs associated start from 0x0013:
0013 : 38                      begin   SEC
0014 : 90 F8                             BCC LABEL
0016 : A9 00                            LDA #$00
0018 : 85 00                            STA $00
001A : 18                                CLC
001B : 90 F1                            BCC LABEL
001D : A9 01                           LDA #$01
001F : 85 01                            STA $01
0021 : A9 02              LABEL    LDA #$02
0023 : 85 02                            STA $02
0025 : 18                                 CLC

The label "LABEL" however is assigned a pc of 0x000E
LABEL ADDED :  BEGIN  -  0000
LABEL ADDED :  LABEL  -  000E

What appears to be happening is that the pc is incrementing during the first pass and assigning the correct pc value to the labels but it is not being reset between passes so the pc assigned to the instructions starts wherever it finished on the first pass.

This causes an issue when the branches use relative addressing since it believes its at pc 0x0014 and that the label is at 0x000E. you can see above the relitive address is calculated to be F8 for the first branch and F1 for the second when they should be 0B and 04.

I was able to correct this issue by adding "pc = 0" at line 195

**Comment by SYSPROG-JLS** [comment]
Hi Sam,
Thanks for using my 6502 assembler. Glad you find it useful.

After looking at this issue, I discovered that the only thing lacking is better documentation.
You need to have a ".org" directive and a ".end" directive in your source code for the assembler to
function correctly.

This is not spelled out in the README.MD file and will be corrected.

Here is my test:
Your code first with the accompanying lst file; then mine:

c:\MyPython\6502Asm>type test3.asm
; Sam Baker
; 10/2023
; Tests stack operations
; Written for use with asm6502 assembler
;
;
; Test: BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS
;
; Program:

begin SEC
      BCC LABEL
      LDA #$00
      STA $00
      CLC
      BCC LABEL
      LDA #$01
      STA $01
LABEL LDA #$02
      STA $02
      CLC

c:\MyPython\6502Asm>

C:\Users\JimS>cd c:\MyPython\6502Asm

c:\MyPython\6502Asm>py -3 asm6502.py test3.asm
'*********************************************
'*  JLS 6502 Assembler                       *
'*  Copyright (c) 2022 James Salvino.        *
'*********************************************
; Sam Baker
; 10/2023
; Tests stack operations
; Written for use with asm6502 assembler
;
;
; Test: BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS
;
; Program:

0013 : 38                 begin SEC
0014 : 90 F8                    BCC LABEL
0016 : A9 00                    LDA #$00
0018 : 85 00                    STA $00
001A : 18                       CLC
001B : 90 F1                    BCC LABEL
001D : A9 01                    LDA #$01
001F : 85 01                    STA $01
0021 : A9 02              LABEL LDA #$02
0023 : 85 02                    STA $02
0025 : 18                       CLC

Creating Intel hex file
Intel hex file created

All Done

c:\MyPython\6502Asm>

===================================================

c:\MyPython\6502Asm>type test3.asm
; Sam Baker
; 10/2023
; Tests stack operations
; Written for use with asm6502 assembler
;
;
; Test: BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS
;
; Program:

      .org $0013
begin SEC
      BCC LABEL
      LDA #$00
      STA $00
      CLC
      BCC LABEL
      LDA #$01
      STA $01
LABEL LDA #$02
      STA $02
      CLC
          .end
c:\MyPython\6502Asm>

c:\MyPython\6502Asm>py -3 asm6502.py test3.asm
'*********************************************
'*  JLS 6502 Assembler                       *
'*  Copyright (c) 2022 James Salvino.        *
'*********************************************
Pass 1 Complete - No Errors Encountered

; Sam Baker
; 10/2023
; Tests stack operations
; Written for use with asm6502 assembler
;
;
; Test: BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS
;
; Program:

pc = 19                         .org $0013
0013 : 38                 begin SEC
0014 : 90 0b                    BCC LABEL
0016 : A9 00                    LDA #$00
0018 : 85 00                    STA $00
001A : 18                       CLC
001B : 90 04                    BCC LABEL
001D : A9 01                    LDA #$01
001F : 85 01                    STA $01
0021 : A9 02              LABEL LDA #$02
0023 : 85 02                    STA $02
0025 : 18                       CLC
0026                              .end

Pass 2 Complete - No Errors Encountered

Assembly Complete

Creating Intel hex file
Intel hex file created

All Done

c:\MyPython\6502Asm>

**Comment by SamBaker101** [comment]
Thanks for your quick response, I added the .org and it looks to be working correctly. Ill let you know if I have any other issues
